# Generated by Django 6.0.6 on 2026-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80),
        ),
    ]
